genome: "workflow/data/iGenome_mm10_ucsc_genes.gtf.gz"
whole_gonad_RNAseq: "workflow/data/Zhao_tpm_matrix_for_analysis.csv"
protein_genes: "workflow/data/mart_prot_coding_genes.txt"
marker_genes: "workflow/data/gonad_marker_genes.csv"
TF_genes: "workflow/data/mouse_transcription_factors.txt"
TF_pheno: "workflow/data/genes_gonad_asociated_pheno_MGI.txt"


RNA_counts: "workflow/data/RNA_XX_Enh8-mCherry_XY_SOX9-IRES-GFP_read_count.csv"
RNA_TPM: "workflow/data/RNA_XX_Enh8-mCherry_XY_SOX9-IRES-GFP_TPM.csv"
RNA_outliers: "E11.5_XX_enh8.mcherry_rep2"
RNA_minReads: 15
RNA_minTPM: 2
RNA_corr_met: "spearman"
RNA_adjpval: 0.01
RNA_log2FC: 0.5
RNA_sex_double_heatmap_clusters: 8
RNA_XX_stage_DEG_clusters: 6
RNA_XY_stage_DEG_clusters: 6


ATAC_counts: "workflow/data/ATAC_XX_Enh8-mCherry_XY_SOX9-IRES-GFP_read_count.csv"
ATAC_promoter_distance: 3000
ATAC_minReads: 5
ATAC_corr_met: "spearman"
ATAC_adjpval: 0.01
ATAC_log2FC: 1
ATAC_XX_stage_DAR_clusters: 4
ATAC_XY_stage_DAR_clusters: 4

MULTI_peak_gene_distance: 500000
MULTI_peak_gene_min_cor: 0.6
MULTI_peak_gene_FDR: 0.05
