# Can be either "mm10" or "mm39"
# Overwrite using --config genome_version="mmxx" when running the pipeline
genome_version: "mm10"

path_to_data: "workflow/data/"
path_to_process: "results/processed_data/"
path_to_tables: "results/tables/"
path_to_graphs: "results/graphs/"

protein_genes: "workflow/data/mart_prot_coding_genes.txt"
marker_genes: "workflow/data/gonad_marker_genes.csv"
TF_genes: "workflow/data/mouse_transcription_factors.txt"
TF_pheno: "workflow/data/TF_gonad_pheno.tsv"
peak_examples: "workflow/data/gTrack_gene_examples.tsv"
gene_peak_examples: "workflow/data/peak2gene_query.tsv"

whole_gonad_RNAseq: "Zhao_tpm_matrix_for_analysis.csv"

RNA_counts: "RNA_XX_Enh8-mCherry_XY_SOX9-IRES-GFP_read_count.csv"
RNA_TPM: "RNA_XX_Enh8-mCherry_XY_SOX9-IRES-GFP_TPM.csv"
RNA_outliers: "E11.5_XX_enh8.mcherry_rep2"
RNA_minReads: 15
RNA_minTPM: 5
RNA_corr_met: "spearman"
RNA_adjpval: 0.01
RNA_log2FC: 0.5
RNA_sex_double_heatmap_clusters: 8
RNA_XX_stage_DEG_clusters: 6
RNA_XY_stage_DEG_clusters: 6
RNA_bigwig_folder_mm10: "/home/istevant/work/data/RNAseq/bigwig_mm10"
RNA_bigwig_folder_mm39: "/home/istevant/work/data/.../bigwig"


ATAC_counts: "ATAC_XX_Enh8-mCherry_XY_SOX9-IRES-GFP_read_count.csv"
ATAC_promoter_distance: 1000
ATAC_minReads: 50
ATAC_corr_met: "spearman"
ATAC_adjpval: 0.01
ATAC_log2FC: 1
ATAC_XX_stage_DAR_clusters: 4
ATAC_XY_stage_DAR_clusters: 4
ATAC_bigwig_folder_mm10: "/home/istevant/work/data/ATACseq/240521_XX-enh8_XY-sox9_sub/mapping_nf-core_atacseq_v2.1.2_GRCm38/bwa/merged_library/bigwig"
ATAC_bigwig_folder_mm39: "/home/istevant/work/data/ATACseq/240521_XX-enh8_XY-sox9_sub/mapping_nf-core_atacseq_v2.1.2_GRCm39/bwa/merged_library/bigwig"

DAR_peak_examples_XX: "workflow/data/gTrack_XX_DAR_peak_examples.tsv"
DAR_peak_examples_XY: "workflow/data/gTrack_XY_DAR_peak_examples.tsv"

MULTI_peak_gene_distance: 500000
MULTI_peak_gene_min_cor: 0.7
MULTI_peak_gene_FDR: 0.01

